//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchyMobileService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.WindowsAzure.Mobile.Service.Tables;
    using System.ComponentModel.DataAnnotations;
    
    
    public partial class CalibrationRecord
    {
        public int ID { get; set; }
        public string MaxInches { get; set; }
        public string MaxGallons { get; set; }
        public string TripInches { get; set; }
        public string TripGallons { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int FlowswitchID { get; set; }
        public string Note { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
    
        public virtual Flowswitch Flowswitch { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual Technician Technician { get; set; }

        //Mobile Service Class
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Index]
        [TableColumn(TableColumnType.CreatedAt)]
        public DateTimeOffset? CreatedAt { get; set; }

        [TableColumn(TableColumnType.Deleted)]
        public bool Deleted { get; set; }

        [Index]
        [TableColumn(TableColumnType.Id)]
        [MaxLength(36)]
        public string Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [TableColumn(TableColumnType.UpdatedAt)]
        public DateTimeOffset? UpdatedAt { get; set; }

        [TableColumn(TableColumnType.Version)]
        [Timestamp]
        public byte[] Version { get; set; }
    }
}
