//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchyMobileService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calibration
    {
        public int ID { get; set; }
        public string MaxInches { get; set; }
        public string MaxGallons { get; set; }
        public string TripInches { get; set; }
        public string TripGallons { get; set; }
        public Nullable<int> TechnicainID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
