//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchyMobileService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using Microsoft.WindowsAzure.Mobile.Service.Tables;
    using System.ComponentModel.DataAnnotations;
    
    
    public partial class Flowswitch
    {
        public Flowswitch()
        {
            this.CalibrationRecords = new HashSet<CalibrationRecord>();
            this.FlowswitchNotes = new HashSet<FlowswitchNote>();
        }
        [Key]
        public int ID { get; set; }
        public int AreaID { get; set; }
        public int LocationID { get; set; }
        public int VenturiID { get; set; }
        public int WaterID { get; set; }
        public int SubsystemID { get; set; }
        public int TypeID { get; set; }
        public int DetailID { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
        public Nullable<int> FlowswitchMakeID { get; set; }
        public Nullable<int> FlowswitchModelID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<CalibrationRecord> CalibrationRecords { get; set; }
        public virtual FlowswitchMake FlowswitchMake { get; set; }
        public virtual FlowswitchModel FlowswitchModel { get; set; }
        public virtual Location Location { get; set; }
        public virtual SubSystem SubSystem { get; set; }
        public virtual FlowswitchType FlowswitchType { get; set; }
        public virtual Venturi Venturi { get; set; }
        public virtual WaterSource WaterSource { get; set; }
        public virtual ICollection<FlowswitchNote> FlowswitchNotes { get; set; }


        //Mobile Service Class
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Index]
        [TableColumn(TableColumnType.CreatedAt)]
        public DateTimeOffset? CreatedAt { get; set; }

        [TableColumn(TableColumnType.Deleted)]
        public bool Deleted { get; set; }

        [Index]
        [TableColumn(TableColumnType.Id)]
        [MaxLength(36)]
        public string Id { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [TableColumn(TableColumnType.UpdatedAt)]
        public DateTimeOffset? UpdatedAt { get; set; }

        [TableColumn(TableColumnType.Version)]
        [Timestamp]
        public byte[] Version { get; set; }
    }
}
