//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchyMobileService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowswitchMake
    {
        public FlowswitchMake()
        {
            this.Flowswitches = new HashSet<Flowswitch>();
            this.FlowswitchModels = new HashSet<FlowswitchModel>();
        }
    
        public int ID { get; set; }
        public string Make { get; set; }
    
        public virtual ICollection<Flowswitch> Flowswitches { get; set; }
        public virtual ICollection<FlowswitchModel> FlowswitchModels { get; set; }
    }
}
