//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchyMobileService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowElementType
    {
        public FlowElementType()
        {
            this.FlowElements = new HashSet<FlowElement>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<FlowElement> FlowElements { get; set; }
    }
}
