//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchyMobileService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int ID { get; set; }
        public int FlowswitchID { get; set; }
        public int NoteID { get; set; }
        public int ServiceRequestID { get; set; }
    }
}
