//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchyMobileService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class flowswitch_dbEntities : DbContext
    {
        public flowswitch_dbEntities()
            : base("name=flowswitch_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CalibrationRecord> CalibrationRecords { get; set; }
        public virtual DbSet<Calibration> Calibrations { get; set; }
        public virtual DbSet<Details2> Details2 { get; set; }
        public virtual DbSet<detailsoriginal> detailsoriginals { get; set; }
        public virtual DbSet<Fami> Famis { get; set; }
        public virtual DbSet<FlowElementMake> FlowElementMakes { get; set; }
        public virtual DbSet<FlowElementModel> FlowElementModels { get; set; }
        public virtual DbSet<FlowElement> FlowElements { get; set; }
        public virtual DbSet<FlowElementSize> FlowElementSizes { get; set; }
        public virtual DbSet<FlowElementType> FlowElementTypes { get; set; }
        public virtual DbSet<Flowswitch> Flowswitches { get; set; }
        public virtual DbSet<FlowswitchMake> FlowswitchMakes { get; set; }
        public virtual DbSet<FlowswitchModel> FlowswitchModels { get; set; }
        public virtual DbSet<FlowswitchNote> FlowswitchNotes { get; set; }
        public virtual DbSet<FlowswitchType> FlowswitchTypes { get; set; }
        public virtual DbSet<FlowswitchVoltage> FlowswitchVoltages { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Rotameter> Rotameters { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<SubSystem> SubSystems { get; set; }
        public virtual DbSet<Technician> Technicians { get; set; }
        public virtual DbSet<Venturi> Venturis { get; set; }
        public virtual DbSet<WaterSource> WaterSources { get; set; }
    }
}
