//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowswitchApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrationRecord
    {
        public int ID { get; set; }
        public string MaxInches { get; set; }
        public string MaxGallons { get; set; }
        public string TripInches { get; set; }
        public string TripGallons { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int FlowswitchID { get; set; }
        public string Note { get; set; }
        public Nullable<int> ServiceRequestID { get; set; }
    
        public virtual Flowswitch Flowswitch { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
