//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowswitchApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowElementModel
    {
        public FlowElementModel()
        {
            this.FlowElementSizes = new HashSet<FlowElementSize>();
        }
    
        public int ID { get; set; }
        public int FlowElementMakeID { get; set; }
        public string Model { get; set; }
    
        public virtual FlowElementMake FlowElementMake { get; set; }
        public virtual ICollection<FlowElementSize> FlowElementSizes { get; set; }
    }
}
